# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm ci
      
      # Run Test
      - name: Test App
        run: npm run test
      
      # Runs a set of commands to build
      - name: Build
        run: npm run build
      #  
      # store the artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./dist

  # deploy job   
  deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    # only run if build job complte successfully 
    needs: [build]
    steps:
      # building the app before deploy
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm ci
      # build the app
      - name: Build the app artifact for prod
        run: npm run build
      # ddeploy the app artifact to firebase
      - name: Deploy angular app to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.personal_fb_token }}
